// This file is automatically generated. Do not modify it.
import { FirebaseOptions } from 'firebase/app';

// TODO: Replace with your actual Firebase project configuration.
// You can find this in the Firebase Console:
// https://console.firebase.google.com/
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDfzLoXMsUeSlmHbfIvYmBoR8Fr5fAIEcs",
  authDomain: "career-compass-ai-4ee1d.firebaseapp.com",
  projectId: "career-compass-ai-4ee1d",
  storageBucket: "career-compass-ai-4ee1d.appspot.com",
  messagingSenderId: "746789996075",
  appId: "1:746789996075:web:f3cc38755d02178f3b0c6e"
};
