// This file is automatically generated. Do not modify it.
import { FirebaseOptions } from 'firebase/app';

// TODO: Replace with your actual Firebase project configuration.
// You can find this in the Firebase Console:
// https://console.firebase.google.com/
export const firebaseConfig: FirebaseOptions = {
  apiKey: 'REPLACE_WITH_YOUR_API_KEY',
  authDomain: 'REPLACE_WITH_YOUR_AUTH_DOMAIN',
  projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
  storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
  messagingSenderId: 'REPLACE_WITH_YOUR_MESSAGING_SENDER_ID',
  appId: 'REPLACE_WITH_YOUR_APP_ID',
};
